<?xml version="1.0"?>
<package format="2">
  <name>moca_teaching_tools</name>
  <version>0.0.1</version>
  <description>Teaching-mode state monitor and recorder for MOCA.</description>

  <maintainer email="wangxiao@example.com">wangxiao</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>hrii_robot_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>pinocchio</depend>
  <depend>robot_dynamic_pin</depend>
  <depend>roscpp</depend>
  <depend>roslib</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tcpip_polytope</depend>
</package>
