# 10N / 80N 双实验对比 plotter 配置
comparison_run_state_topic: "/comparison_run_state"
manipulability_topic: "/wb_cart_imp_controller/manipulability"
directional_force_capacity_topic: "/wb_cart_imp_controller/directional_force_capacity"
desired_force_topic: "/wb_cart_imp_controller/desired_force"
pose_topic: "/wb_cart_imp_controller/moca_pose"
pose_target_topic: "/wb_cart_imp_controller/moca_pose_target"
state_topic: "/wb_cart_imp_controller/moca_state"
state_target_topic: "/wb_cart_imp_controller/moca_state_target"
base_cmd_velocity_topic: "/wb_cart_imp_controller/base_cmd_velocity"

# 窗口与刷新设置
show_window: true
render_rate_hz: 5.0

# 图像保存路径
combined_output_png_path: "$(find polytope_ros)/../../output/polytope_ros/force_sweep_comparison.png"
manipulability_output_png_path: "$(find polytope_ros)/../../output/polytope_ros/force_sweep_manipulability_comparison.png"
force_output_png_path: "$(find polytope_ros)/../../output/polytope_ros/force_sweep_directional_force_comparison.png"
